from graphics import *
new_win = GraphWin('A car with wheels', 400, 400)
p1 = Point(55, 15)
p2 = Point(135, 15)
wheel_front = Circle(p1, 10)
wheel_back = Circle(p2, 10)
car_body1 = Rectangle(p2, Point(p1.x, p1.y + 40))
wheel_front.setFill("Black")
wheel_front.draw( new_win )
wheel_back.setFill("Black")
wheel_back.draw( new_win )
car_body1.setFill("Blue")
car_body1.draw( new_win )
new_win.mainloop() 
